#--------------------------------------------------------------
#                 Makefile for interface module
#--------------------------------------------------------------

# List module object filenames
interface_objects=\
interface.o

# Append module objects to global tree
OBJECTS+=$(addprefix obj/interface/,$(interface_objects))
