#--------------------------------------------------------------
#                 Makefile for interface module
#--------------------------------------------------------------

# List module object filenames
libinput_objects=\
libinput.o

# Append module objects to global tree
OBJECTS+=$(addprefix obj/libinput/,$(libinput_objects))
