#--------------------------------------------------------------
#                 Makefile for cells module
#--------------------------------------------------------------

# List module object filenames
cells_objects=\
data.o

# Append module objects to global tree
OBJECTS+=$(addprefix obj/cells/,$(cells_objects))
