#--------------------------------------------------------------
#                 Makefile for main module
#--------------------------------------------------------------
main_objects=\
main.o

OBJECTS+= $(addprefix obj/main/,$(main_objects))
