#--------------------------------------------------------------
#                 Makefile for utility module
#--------------------------------------------------------------

# List module object filenames
utility_objects=\
random.o

# Append module objects to global tree
OBJECTS+=$(addprefix obj/utility/,$(utility_objects))
