#--------------------------------------------------------------
#                 Makefile for cells module
#--------------------------------------------------------------

# List module object filenames
create_objects=\
create.o \
create_grain_structure.o \
create_single_grain.o \
create_cubic_grain_structure.o \
data.o \
interface.o

#//set_anisotropy.cpp \
#//set_exchange.cpp \
#//set_material.cpp \
#//set_anisotropy_direction.cpp \
#//set_magnetization.cpp \
#//set_Tc.cpp \
#//set_damping.cpp \
#//set_magnetization_direction.cpp


# Append module objects to global tree
OBJECTS+=$(addprefix obj/create/,$(create_objects))
